name : Unified Automation Framework workflow 

on : [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - name : Checkout repository
            uses: actions/checkout@v2
          
          - name: Set up JDK 21
            uses: actions/setup-java@v2
            with:
                java-version: '21'
                distribution: 'adopt'
                cache: 'maven'

          - name: Change working directory
            run: cd ${{ github.workspace }}

          - name: Build and test
            run: mvn clean test  
            
