name : Unified Automation Framework workflow 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker container
      uses: actions/docker@v2
      with:
        image: openjdk:11-jdk-slim
        commands: |
          # Install Maven
          apt-get update && apt-get install -y maven
          
          # Build and test the project
          mvn clean package